### ISSUE TITLE
iCloud Drive not mentioned in iCloud Drive error message

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#3972]
![image_480](https://github.com/Ranchero-Software/NetNewsWire/assets/1297121/a8267d6f-2a4d-4f77-bb2b-d744c659b45a)

**Comment by vincode-io** [comment]
This was resolved in #3610.

**Comment by biggianteye** [comment]
> This was resolved in #3610.

The commit referenced in that issue was made in November 2022 but the message window still does not mention iCloud Drive as of the current version (6.1.2). Do you know what version will have the updated message?

**Comment by itgrrl** [comment]
Still showing the old message in v6.1.4 (6120) as at 2024-01-23

**Comment by brentsimmons** [comment]
Reopening because this needs additional verification.
