### ISSUE TITLE
Refresh progress counts incrementing in macOS 6.1.5

### ISSUE THREAD

**Issue by stncttr908** [Ranchero-Software/NetNewsWire#4415]
After updating my macOS client to 6.1.5 today, running Sequoia 15.1.1, there is a new behavior when refreshing feeds manually or automatically per the refresh feeds interval. The counter "xx of xx" in the lower left is now incrementing the values. For example, I have 11 feeds/groups, upon launching the app it will read "1-11 of 11", the next refresh will display starting at "11 of 22", the next "22 of 33", and so forth. The progress bar is sized to reflect this. This continues until the app is closed and reopened.

First refresh:
<img width="236" alt="Screenshot 2024-12-04 at 2 37 02 PM" src="https://github.com/user-attachments/assets/4efe1ef4-ccc5-487d-a933-ba15b44b7f82">

Second refresh:
<img width="212" alt="Screenshot 2024-12-04 at 2 02 16 PM" src="https://github.com/user-attachments/assets/b5d950ad-1675-45d2-94a3-34c9d6b6b16f">

Some time later:
<img width="201" alt="Screenshot 2024-12-04 at 2 36 20 PM" src="https://github.com/user-attachments/assets/567e378b-1fd3-45f7-b1f7-178040a89f36">

**Comment by brentsimmons** [comment]
What kind of account(s) are you using? (On My Mac, iCloud, Feedbin, Feedly, …)?

**Comment by stncttr908** [comment]
> What kind of account(s) are you using? (On My Mac, iCloud, Feedbin, Feedly, …)?

Just Feedly. "On My Mac" exists of course, but is empty and disabled.

**Comment by brentsimmons** [comment]
This appears to be a Feedly-specific bug. Looking into the cause.

**Comment by brentsimmons** [comment]
Fixed in 1f493963ba681e9286b37ea21bc83cd099f34d3b

**Comment by stncttr908** [comment]
> Fixed in [1f49396](https://github.com/Ranchero-Software/NetNewsWire/commit/1f493963ba681e9286b37ea21bc83cd099f34d3b)

Apologies, but it is still occurring under 6.1.6.

<img width="240" alt="Screenshot 2024-12-05 at 3 36 00 PM" src="https://github.com/user-attachments/assets/b44d54c4-ac71-4002-8e5b-45f5a1fd9450">

**Comment by brentsimmons** [comment]
Nuts! It worked in my testing. Well — I’ll re-open this.

**Comment by stncttr908** [comment]
Thanks, I debated even reopening since it doesn't impact the app's functionality and I'm sure you have better things to spend time on.

**Comment by brentsimmons** [comment]
Always open bugs! They need to get fixed! :)
