### ISSUE TITLE
iCloud: Refresh button and menu item disabled even though no feeds are currently being refreshed

### ISSUE THREAD

**Issue by simX** [Ranchero-Software/NetNewsWire#4538]
macOS Sonoma 14.7.4, NNW Version 6.1.9 (6135)

This is an issue I've noticed every once in a while, and I can't seem to find steps to reproduce or a reliable event that causes this to happen.

Every once in a while, both the refresh button and refresh menu item are disabled.  There are no feeds currently being refreshed (the progress bar is not present in the bottom-left corner of the window), and yet I can't force a manual refresh.  Is there an intentional reason why this happens, or is it a bug?

It's not the biggest deal as there's a workaround: just quit and relaunch NetNewsWire, at which point all feeds auto-refresh and the progress bar appears.  When all feeds are finished refreshing and the progress bar disappears after launch, the refresh button and menu item are correctly enabled.

Here's a screenshot:

![Image](https://github.com/user-attachments/assets/173898d9-a016-4e8d-a0ef-3d94d321ddc0)

**Comment by brentsimmons** [comment]
Which syncing systems are you using?

**Comment by simX** [comment]
iCloud only.

**Comment by michaelsteeber** [comment]
I'm also using iCloud only and facing this same issue. I just set up a new Mac and have not been able to successfully refresh my iCloud feed at all. The issue persists relaunches and reboots. I was considering removing my account and re-adding it in settings, but the language says "delete" account and I'm not sure if this just removes the account or actually deletes it.

**Comment by ednl** [comment]
Same here. New Mac, fresh install of latest stable NNW 6.1.9, add iCloud account => no messages and no way to refresh (also not timed).

Edit: oh! Restarting NNW did not help and I had set updates to 'Manually only' but left NNW open and it suddenly updated after all. So messages are there again, and read status, and the Refresh button is enabled too. ¯\\\_(ツ)_/¯

**Comment by brentsimmons** [comment]
This also happens on iOS, which suggests the bug is in shared code (which is good) — see #4469.

**Comment by brentsimmons** [comment]
I just fixed the likely cause of this. If this continues to happen in 6.2, we can re-open this bug.

**Comment by MauriceBrg** [comment]
Hey, unfortunately this isn't fixed in 6.2 - the Refresh button is still disabled.

<img width="549" height="417" alt="Image" src="https://github.com/user-attachments/assets/bac058c9-6820-44ee-89e5-cb3d35489969" />

**Comment by wongjustin99** [comment]
just FYI i am still experiencing this on Version 7.0.3 (Build 7037)

New mac, pulled in iCloud feed, and cant refresh feeds manually

<img width="271" height="187" alt="Image" src="https://github.com/user-attachments/assets/ceb0a8bd-0a61-4079-abb3-aca4e00c01bd" />

**Comment by brentsimmons** [comment]
Is this still happening? I think this has been fixed, but I want to be sure.

**Comment by wongjustin99** [comment]
This is no longer happening to me. Thanks!

**Comment by simX** [comment]
@brentsimmons I regret to say that I just had this issue happen to me again today, with NetNewsWire 7.1.1 (Build 7108) on macOS Sequoia 15.7.7 (24G720).  This is actually the first time it's happened to me in a loooooong time; any improvements since I first filed this report last year have made this issue much less frequent.  Automatic refresh kicked in a few minutes later, and everything refreshed as usual, and now the refresh button and menu items work again.

Not sure if it's really worth re-opening this issue.  I thought it was completely fixed until today.  It seems like it's a very rare issue for everybody else too, so probably other issues are more important to work on.

**Comment by brentsimmons** [comment]
@simX When this happens, please check the Current Activity and Error Log — Current Activity will tell us if NetNewsWire is doing something, and Error Log will tell us if there were any recent errors that might have triggered this.

**Comment by simX** [comment]
This problem just happened for me again (first time it's happened since my comment above).  There's nothing in Current Activity, and nothing in the error log (besides a few recurring errors for RSS feeds that no longer exist).  Here's a screenshot.  The Activity Log also shows nothing out of the ordinary: the last lines before the time shown in the screenshot are a couple "iCloud: Refreshing statuses" and "iCloud: Sending statuses" and nothing to indicate anything going wrong.  I can send the logs themselves if that would be helpful.

The problem did fix itself again, but this time, not immediately after an automatic refresh but a little bit afterwards.

![Image](https://github.com/user-attachments/assets/39fc7c29-687d-41a6-927b-f771850a9374)

**Comment by brentsimmons** [comment]
Believed to be fixed in 7.1.3.
